name: Build Latex and Publish to GitHub Pages
on: [push]
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Set up Git repository
        uses: actions/checkout@v2
      # Compile Latex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: |
            latexmk -c
            mkdir ./published/
            mv main.pdf ./published/main.pdf
      # Upload it as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: ./published/main.pdf
