name: Build Latex and Publish to GitHub Pages
on: [push]
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Set up Git repository
        uses: actions/checkout@v2
      # Compile Latex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          pre_compile: mkdir ./published/
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: |
            mkdir ./published/
            mv main.pdf ./published/main.pdf
            latexmk -c
#       # Upload it as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: notes.pdf
          path: ./published/main.pdf
#       # Publish it as a GitHub Page
#       - name: Publish generated content to GitHub Pages
#         uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
#         with:
#           dir: ./published/
#           branch: main
#           token: ${{ secrets.ACCESS_TOKEN }}
